### PR TITLE
don't bundle dist.ini in distribution

### PR DESCRIPTION
**Pull request by yanick**

### CODE REVIEW

**Comment by phochste** [comment]
Thanks!

**Comment by jorol** [comment]
Hi Yanick,

could you please give some infos why the dist.ini shouldn't be bundled in distributions? As I see this is common practise in many distributions.

Thanks,

Johann

**Comment by yanick** [comment]
Hi @jorol!

Having the dist.ini bundle with the distribution does no harm, but it is useless baggage. It's like installing the Makefile along with the program. And in almost all cases, it couldn't be used against the files as bundled in the distribution (as opposed as against the files in the repo) as 'dzil build' is not usually idempotent.

**Comment by jorol** [comment]
Thanks!

**Comment by yanick** [comment]
Anytime. :-)

**Pull request merged**
